// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnersHub.InnovationHub.Infrastructure.Presistence;

#nullable disable

namespace PartnersHub.InnovationHub.Infrastructure.Presistence.Migrations
{
    [DbContext(typeof(InnovationHubDbContext))]
    [Migration("20251101140940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedSectorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssociatedSectorId");

                    b.Property<int>("ChallengeStatus")
                        .HasColumnType("int")
                        .HasColumnName("ChallengeStatus");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("PriorityLevelId")
                        .HasColumnType("int")
                        .HasColumnName("PriorityLevelId");

                    b.Property<Guid>("SourceCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SourceCompanyId");

                    b.Property<string>("SubmitterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubmitterName");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedSectorId");

                    b.HasIndex("SourceCompanyId");

                    b.ToTable("ChallengeRequests", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AssociatedProviders", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedSector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AssociatedSectors", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeRequestId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SharePointFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SharePointLibrary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeRequestId");

                    b.HasIndex("ChallengeRequestId1");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UploadedAt");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestRevisionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeRequestId");

                    b.ToTable("challengeRequestRevisionComments");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeTrackingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challengeTrackingHistories");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest.ChallengeTechnologiesRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustificationForLinking")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("ChallengeRequestId", "TechnologyId")
                        .IsUnique();

                    b.ToTable("challengeTechnologiesRequests");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnologyStage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeRequestId");

                    b.ToTable("technologies");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedSector", "AssociatedSector")
                        .WithMany()
                        .HasForeignKey("AssociatedSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedProvider", "SourceCompany")
                        .WithMany()
                        .HasForeignKey("SourceCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedSector");

                    b.Navigation("SourceCompany");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAttachment", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany()
                        .HasForeignKey("ChallengeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ChallengeRequestId1");

                    b.OwnsOne("PartnersHub.InnovationHub.Domain.ValueObjects.Attachment", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ChallengeRequestAttachmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("int")
                                .HasColumnName("Extension");

                            b1.Property<int>("Format")
                                .HasMaxLength(100)
                                .HasColumnType("int")
                                .HasColumnName("Format");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Name");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("SizeInBytes");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ChallengeRequestAttachmentId");

                            b1.ToTable("Attachments");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRequestAttachmentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestRevisionComment", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("RevisionComments")
                        .HasForeignKey("ChallengeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeTrackingHistory", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("TrackingHistory")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest.ChallengeTechnologiesRequest", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest.Technology", "LinkedTechnology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LinkedTechnology");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest.Technology", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("Technologies")
                        .HasForeignKey("ChallengeRequestId");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("RevisionComments");

                    b.Navigation("Technologies");

                    b.Navigation("TrackingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
